### ISSUE TITLE
LTP-PIC

### ISSUE THREAD

**Issue by jianyi324** [tpowis/ltp_pic_hack24#1]
Dear tpowis,

I am interested in the simulation of LTP. Where can I get the source code of LTP-PIC?

Best regards！

**Comment by tpowis** [comment]
Hi jianyi324

Currently the full source code of LTP-PIC is not available, however we are hoping to have it available in the coming months. I will aim to let you know when this occurs.

Cheers,

tpowis

**Comment by jianyi324** [comment]
Okay, thanks. Looking forward to your notice.
